### ISSUE TITLE
Problem z kolorem.

### ISSUE THREAD

**Issue by Milo46** [Milo46/Projekt-2e4#5]
@krisior pomóż. Ten głupi kolor nie działa! Zrób go na niebieski. 886f3a3

**Comment by krisior** [comment]
Done! Dziękujemy za szybką informację :D

**Comment by krisior** [comment]
Niestety, po rozpatrzeniu problemu nie może zostać on dokładnie zidentyfikowany, co uniemożliwia dalsze działania.
Przepraszamy za nieudogodnienia 😞 


MAAJKeL Studios/GitHub © Copyright 2020-2021

**Comment by Milo46** [comment]
Ty mi tutaj się nie wymiguj, ty leniuchu.
